name: build android

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
          architecture: x64
      - run: |
          flutter pub get
          flutter build apk --release --target-platform=android-arm64
#      - uses: actions/upload-artifact@v3
#        with:
#          name: flutter_apk
#          path: build\app\outputs\flutter-apk\app-release.apk
      - name: Upload File
        id: myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'http://115.159.28.38:10008/other/upload'
          method: 'POST'
          file: build\app\outputs\flutter-apk\app-release.apk
      - name: Show Response
        run: |
          echo ${{ steps.myRequest.outputs.response }}
          echo ${{ steps.myRequest.outputs.headers }}
          echo ${{ fromJson(steps.myRequest.outputs.response).data }}    

