name: publish android

on:
  push:
    tags:
      - 'v*.*.*'

env:
  NAME: luoyi_flutter

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
      - run: |
          flutter pub get
          flutter build apk --release --target-platform=android-arm64
      - name: Get Upload Token
        id: getUploadToken
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'http://115.159.28.38:10008/getUploadToken?fileName=${{ env.NAME }}_${{ steps.tag.outputs.tag }}.apk'
          method: 'GET'
      - name: Echo Response Token
        run: |
          echo ${{ steps.getUploadToken.outputs.response }}
          echo ${{ fromJson(steps.getUploadToken.outputs.response) }}
      - name: Upload File
        id: uploadFile
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'http://upload-z2.qiniup.com'
          method: 'POST'
          customHeaders: '{"Content-Type": "multipart/form-data"}'
          data: '{"token":"${{ fromJson(steps.getUploadToken.outputs.response).data }}","key":"${{ env.NAME }}_${{ steps.tag.outputs.tag }}.apk"}'
          files: '{"file":"build/app/outputs/flutter-apk/app-release.apk"}'
          timeout: 30000
          retry: 3
          retryWait: 3000
      - name: Insert Upload Data
        id: insertUploadData
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'http://115.159.28.38:10008/app-version'
          method: 'POST'
          data: '{"appName":"${{ fromJson(steps.uploadFile.outputs.response).key }}","versionName":"${{ steps.tag.outputs.tag }}"},"fileSize":"${{ fromJson(steps.uploadFile.outputs.response).fsize }}"'
          retry: 3
          retryWait: 3000
      - name: Release apk
        uses: ncipollo/release-action@v1.5.0
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          token: ${{ secrets.github_token }}
